# Generated by Django 4.0.4 on 2022-10-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mentor_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentor',
            new_name='Partner',
        ),
    ]
